# Introduction to NumPy

## Meet NumPy

### Welcome

NumPy: Numerical Python

Why NumPy?

* It's faster.
* It depends on array programming paradigm.  You don't have to loop over data.
* Additional concepts:
    * Linear algebra
    * Matrix multiplication
    * Fourier transformations

## Getting Setup

Best way: use Anaconda, a distribution of all popular Python data libraries.

Create a new environment:

    conda create -n 100days numpy jupyter
    
Activate environment:

    conda activate 100days
    
where "100days" is the name of the environment.

Open up Jupyter server:

    jupyter notebook

In [1]:
# Import as np
import numpy as np

In [2]:
np.__version__

'1.16.2'

### Introducing Arrays

Arrays:
* More restrictive than lists; every item must be same data type.
* Arrays length can't be changed; size cannot be changed and must be defined when you create array.
* Less overhead than lists.
* Elements are contiguous.

#### Lists

In [3]:
gpas_as_list = [4.0, 3.286, 3.5]

In [4]:
# Can append
gpas_as_list.append(4.0)

In [5]:
# Can insert different data types
gpas_as_list.insert(1, "Whatevs")

In [6]:
# Can remove
gpas_as_list.pop(1)

'Whatevs'

In [7]:
gpas_as_list

[4.0, 3.286, 3.5, 4.0]

#### Arrays

In [8]:
gpas = np.array(gpas_as_list)
gpas

array([4.   , 3.286, 3.5  , 4.   ])

In [9]:
# Peep at documentation:
?gpas

In [10]:
# Describe format of elements in array:
gpas.dtype

dtype('float64')

In [11]:
# Memory use (bytes) - 64 bits = 8 bytes:
gpas.itemsize

8

In [12]:
# No. of elements:
gpas.size

4

In [13]:
len(gpas)

4

In [14]:
# Total number of bytes (8 bytes * 4 elements):
gpas.nbytes

32

#### Differences between lists and NumPy Arrays
* An array's size is immutable.  You cannot append, insert or remove elements, like you can with a list.
* All of an array's elements must be of the same [data type](https://docs.scipy.org/doc/numpy-1.14.0/user/basics.types.html).
* A NumPy array behaves in a Pythonic fashion.  You can `len(my_array)` just like you would assume.

#### Quiz
* Create a new array by passing an iterable, and an array is Pythonic, so you can pass it to the len function.
* Create array with elements 1, 2, 3: np.array([1, 2, 3])
* A list can have items appended, inserted, and removed; an array cannot. 

### Creating the Study Log

Create an array populated with zeros, e.g., 100 elements:

In [15]:
# Default is floating point:
study_min = np.zeros(100)
study_min

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
# Jupyter Notebook special command
%whos

Variable       Type       Data/Info
-----------------------------------
gpas           ndarray    4: 4 elems, type `float64`, 32 bytes
gpas_as_list   list       n=4
np             module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
study_min      ndarray    100: 100 elems, type `float64`, 800 bytes


In [17]:
minutes_in_day = 24 * 60
minutes_in_day

1440

In [18]:
# Unsigned integers take less space:
study_minutes = np.zeros(100, np.uint16)
study_minutes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

In [19]:
%whos

Variable         Type       Data/Info
-------------------------------------
gpas             ndarray    4: 4 elems, type `float64`, 32 bytes
gpas_as_list     list       n=4
minutes_in_day   int        1440
np               module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
study_min        ndarray    100: 100 elems, type `float64`, 800 bytes
study_minutes    ndarray    100: 100 elems, type `uint16`, 200 bytes


In [20]:
study_minutes[0] = 150
first_day_minutes = study_minutes[0]
first_day_minutes

150

In [21]:
type(first_day_minutes)

numpy.uint16

Data types:
* Scalar: representing a singular value; single element
* Vector: multiple elements

In [22]:
study_minutes[1] = 60
second_day_minutes = study_minutes[1]
second_day_minutes

60

In [23]:
# To add 4 elements, start with the actual array location, then add 4 to get 6:
study_minutes[2:6] = [80, 60, 30, 90]
study_minutes

array([150,  60,  80,  60,  30,  90,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0], dtype=uint16)

ndarray: n-dimensional array

#### Quiz
* Vector: single dimension array
* Scalar: one of the elements in the array

### Multidimensional Arrays

Rank: number of dimensions an array has

Matrix: array with 2 dimensions (vector: 1)

In [24]:
students_gpas = np.array([
    [4.0, 3.286, 3.5, 4.0],
    [3.2, 3.8, 4.0, 4.0],
    [3.96, 3.92, 4.0, 4.0],
], np.float16)
students_gpas

array([[4.   , 3.285, 3.5  , 4.   ],
       [3.2  , 3.8  , 4.   , 4.   ],
       [3.96 , 3.92 , 4.   , 4.   ]], dtype=float16)

#### About data types

* By choosing the proper [data type](https://docs.scipy.org/doc/numpy-1.14.0/user/basics.types.html) you can greatly reduce the size required to store objects
* Data types are maintained by wrapping values in a [scalar representation](https://docs.scipy.org/doc/numpy-1.14.0/reference/arrays.scalars.html)
* `np.zeros` is a handy way to create an empty array filled with zeros.

In [25]:
# Get the number of dimensions:
students_gpas.ndim

2

In [26]:
# Get the number of elements in each dimension, i.e., length of axes
students_gpas.shape

(3, 4)

In [27]:
# Total number of elements
students_gpas.size

12

In [28]:
# How many bytes used for each item:
students_gpas.itemsize

2

In [29]:
# Total size
total_size = students_gpas.size * students_gpas.itemsize
total_size

24

In [30]:
%whos ndarray

Variable        Type       Data/Info
------------------------------------
gpas            ndarray    4: 4 elems, type `float64`, 32 bytes
students_gpas   ndarray    3x4: 12 elems, type `float16`, 24 bytes
study_min       ndarray    100: 100 elems, type `float64`, 800 bytes
study_minutes   ndarray    100: 100 elems, type `uint16`, 200 bytes


In [31]:
# NumPy function: get information on any NumPy object
np.info(students_gpas)

class:  ndarray
shape:  (3, 4)
strides:  (8, 2)
itemsize:  2
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x1597bd3cc70
byteorder:  little
byteswap:  False
type: float16


In [32]:
students_gpas[2]

array([3.96, 3.92, 4.  , 4.  ], dtype=float16)

In [33]:
students_gpas[2][3]

4.0

#### Multidimensional Arrays

* The data structure is actually called `ndarray`, representing any **n**umber of **d**imensions
* Arrays can have multiple dimensions, you declare them on creation
* Dimensions help define what each element in the array represents.  A two dimensional array is just an array of arrays
* **Rank** defines how many dimensions an array contains 
* **Shape** defines the length of each of the array's dimensions
* Each dimension is also referred to as an **axis**, and they are zero-indexed. Multiples are called **axes**.
* A 2d array is AKA **matrix**.

## Array Organization

### Indexing

In [34]:
study_minutes

array([150,  60,  80,  60,  30,  90,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0], dtype=uint16)

In [35]:
study_minutes = np.array([
    study_minutes,
    np.zeros(100, np.uint16)
])

In [36]:
study_minutes.shape

(2, 100)

In [37]:
# Set round 2 day 1 to 60
study_minutes[1][0] = 60
study_minutes

array([[150,  60,  80,  60,  30,  90,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 60,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [38]:
# NumPy shortcut: use tuple instead
study_minutes[1, 0]

60

#### Fancy Indexing

Resulting array shape matches index array layout.  Be careful to distinguish between tuple shortcut and fancy indexing.

RandomState: seed randomness in a way that's repeatable.

In [39]:
# Random number generator
rand = np.random.RandomState(42)
fake_log = rand.randint(30, 180, size=100, dtype=np.uint16)
fake_log

array([132, 122, 128,  44, 136, 129, 101,  95,  50, 132, 151,  64, 104,
       175, 117, 146, 139, 129, 133, 176,  98, 160, 179,  99,  82, 142,
        31, 106, 117,  56,  98,  67, 121, 159,  81, 170,  31,  50,  49,
        87, 179,  51, 116, 177, 118,  78, 171, 117,  88, 123, 102,  44,
        79,  31, 108,  80,  59, 137,  84,  93, 155, 160,  67,  80, 166,
       164,  70,  50, 102, 113,  47, 131, 161, 118,  82,  89,  81,  43,
        81,  38, 119,  52,  82,  31, 159,  57, 113,  71, 121, 140,  91,
        70,  37, 106,  64, 127, 110,  58,  93,  79], dtype=uint16)

In [40]:
[fake_log[3], fake_log[8]]

[44, 50]

In [41]:
[fake_log[[3, 8]]]

[array([44, 50], dtype=uint16)]

In [42]:
index = np.array([
    [3, 8],
    [0, 1]
])
fake_log[index]

array([[ 44,  50],
       [132, 122]], dtype=uint16)

In [43]:
# Error: all input arrays must have same number of dimensions
# study_minutes = np.append(study_minutes, fake_log, axis=0)

# Solve by making a list of lists:
study_minutes = np.append(study_minutes, [fake_log], axis=0)

In [44]:
study_minutes[1, 1] = 360
study_minutes

array([[150,  60,  80,  60,  30,  90,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 60, 360,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

#### Code Challenge

In [45]:
quarterly_revenue = np.array([22.72, 29.13, 25.36, 35.75])
quarterly_revenue[[1, 3]]

array([29.13, 35.75])

In [46]:
quarterly_revenue_by_year = np.array([
    [22.72, 29.13, 25.36, 35.75],
    [29.13, 30.4, 32.71, 43.74],
    [35.71, 37.96, 43.74, 60.5]
])
quarterly_revenue_by_year[1, 3]

43.74

#### Creation 
* You can create a random but bound grouping of values using the `np.random` package.  
  * `RandomState` let's you seed your randomness in a way that is repeatable.
* You can append a row in a couple of ways
   * You can use the `np.append` method.  Make sure the new row is the same shape.
   * You can create/reassign a new array by including the existing array as part of the iterable in creation.


#### Indexing
* You can use an indexing shortcut by separating dimensions with a comma.  
* You can index using a `list` or `np.array`.  Values will be pulled out at that specific index.  This is known as fancy indexing.
  * Resulting array shape matches the index array layout.  Be careful to distinguish between the tuple shortcut and fancy indexing.

### Boolean Array Indexing

* You can create a boolean array by using comparison operators on an array.
  * You can use boolean arrays for fancy indexing.
  * Boolean arrays can be compared by using bitwise operators (`&`, `|`)
      * Do not use the `and` keyword.
      * Remember to mind the order of operations when combining
* Even though boolean indexing returns a new array, you can update an existing array using a boolean index

In [47]:
fake_log

array([132, 122, 128,  44, 136, 129, 101,  95,  50, 132, 151,  64, 104,
       175, 117, 146, 139, 129, 133, 176,  98, 160, 179,  99,  82, 142,
        31, 106, 117,  56,  98,  67, 121, 159,  81, 170,  31,  50,  49,
        87, 179,  51, 116, 177, 118,  78, 171, 117,  88, 123, 102,  44,
        79,  31, 108,  80,  59, 137,  84,  93, 155, 160,  67,  80, 166,
       164,  70,  50, 102, 113,  47, 131, 161, 118,  82,  89,  81,  43,
        81,  38, 119,  52,  82,  31, 159,  57, 113,  71, 121, 140,  91,
        70,  37, 106,  64, 127, 110,  58,  93,  79], dtype=uint16)

In [48]:
fake_log < 60

array([False, False, False,  True, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False,  True, False, False, False, False, False, False,
        True,  True,  True, False, False,  True, False, False, False,
       False, False, False, False, False, False,  True, False,  True,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False,  True, False, False,  True, False,
       False, False, False, False, False,  True, False,  True, False,
        True, False,  True, False,  True, False, False, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False])

In [49]:
fake_log[fake_log < 60]

array([44, 50, 31, 56, 31, 50, 49, 51, 44, 31, 59, 50, 47, 43, 38, 52, 31,
       57, 37, 58], dtype=uint16)

In [50]:
results = []
for value in fake_log:
    if value < 60:
        results.append(value)
np.array(results)

array([44, 50, 31, 56, 31, 50, 49, 51, 44, 31, 59, 50, 47, 43, 38, 52, 31,
       57, 37, 58], dtype=uint16)

In [51]:
study_minutes < 60

array([[False, False, False, False,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  Tru

In [52]:
# Returns 1 dimensional array, not 3 dimensional
study_minutes[study_minutes < 60]

array([30,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, 44, 50, 31, 56, 31, 50, 49, 51, 44, 31, 59,
       50, 47, 43, 38, 52, 31, 57, 37, 58], dtype=uint16)

In [53]:
np.array([False, True, True]) & np.array([True, False, True])

array([False, False,  True])

In [54]:
study_minutes[(study_minutes < 60) & (study_minutes > 0)]

array([30, 44, 50, 31, 56, 31, 50, 49, 51, 44, 31, 59, 50, 47, 43, 38, 52,
       31, 57, 37, 58], dtype=uint16)

In [55]:
# Set to 0:
study_minutes[study_minutes < 60] = 0
study_minutes[2]

array([132, 122, 128,   0, 136, 129, 101,  95,   0, 132, 151,  64, 104,
       175, 117, 146, 139, 129, 133, 176,  98, 160, 179,  99,  82, 142,
         0, 106, 117,   0,  98,  67, 121, 159,  81, 170,   0,   0,   0,
        87, 179,   0, 116, 177, 118,  78, 171, 117,  88, 123, 102,   0,
        79,   0, 108,  80,   0, 137,  84,  93, 155, 160,  67,  80, 166,
       164,  70,   0, 102, 113,   0, 131, 161, 118,  82,  89,  81,   0,
        81,   0, 119,   0,  82,   0, 159,   0, 113,  71, 121, 140,  91,
        70,   0, 106,  64, 127, 110,   0,  93,  79], dtype=uint16)

#### Code Challenge

In [56]:
cat_counts = np.array([1, 0, 2, 6, 5, 2, 1, 3, 18, 1, 2])

In [57]:
cat_counts[cat_counts > 2]

array([ 6,  5,  3, 18])

In [58]:
potential_adoptees = cat_counts[(cat_counts >= 1) & (cat_counts < 5)]

In [59]:
potential_adoptees

array([1, 2, 2, 1, 3, 1, 2])

Remember: & does element by element comparisons, while and tries to make things a scalar truthy value.

### Slicing

* Works a lot like normal list slicing.
* You can use commas to separate each dimension slice.
* Always returns a data view
* You can access the base object using the `ndarray.base` property

In [60]:
fruit = ["apple", "banana", "cherry", "durian"]

In [61]:
fruit[1:3]

['banana', 'cherry']

In [62]:
fruit[:3]

['apple', 'banana', 'cherry']

In [63]:
fruit[3:]

['durian']

In [64]:
fruit[:]

['apple', 'banana', 'cherry', 'durian']

In [65]:
# Slicing a list returns a copy:
copied = fruit[:]
copied[3] = "cheese"
fruit, copied

(['apple', 'banana', 'cherry', 'durian'],
 ['apple', 'banana', 'cherry', 'cheese'])

In [66]:
fruit[::2]

['apple', 'cherry']

In [67]:
fruit[::-1]

['durian', 'cherry', 'banana', 'apple']

In [69]:
# Like Python's range function, but arange returns an ndarray
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [71]:
practice = np.arange(42)
practice.shape = (7,6)
practice

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

In [72]:
practice[2][1]

13

In [75]:
practice[2, 1]

13

In [76]:
# You can slice:
practice[2:5]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [77]:
# Get a particular column
practice[2:5, 3]

array([15, 21, 27])

In [78]:
practice[2:5, 3:]

array([[15, 16, 17],
       [21, 22, 23],
       [27, 28, 29]])

In [79]:
practice[2:5, 3::2]

array([[15, 17],
       [21, 23],
       [27, 29]])

In [83]:
# Any slicing of ndarray returns a view and not a copy!
not_copied = practice[:]

# not_copied is a data view
not_copied[0, 0] = 90210
practice, not_copied

(array([[90210,     1,     2,     3,     4,     5],
        [    6,     7,     8,     9,    10,    11],
        [   12,    13,    14,    15,    16,    17],
        [   18,    19,    20,    21,    22,    23],
        [   24,    25,    26,    27,    28,    29],
        [   30,    31,    32,    33,    34,    35],
        [   36,    37,    38,    39,    40,    41]]),
 array([[90210,     1,     2,     3,     4,     5],
        [    6,     7,     8,     9,    10,    11],
        [   12,    13,    14,    15,    16,    17],
        [   18,    19,    20,    21,    22,    23],
        [   24,    25,    26,    27,    28,    29],
        [   30,    31,    32,    33,    34,    35],
        [   36,    37,    38,    39,    40,    41]]))

In [87]:
# Look at base property to see if a data type is a view (False)
practice.base is None

True

In [88]:
not_copied.base is None

False

In [89]:
not_copied.base is practice

True

In [90]:
practice.flags['OWNDATA'], not_copied.flags['OWNDATA']

(True, False)

In [92]:
# Copy practice
practice_copied = practice.copy()
practice_copied

array([[90210,     1,     2,     3,     4,     5],
       [    6,     7,     8,     9,    10,    11],
       [   12,    13,    14,    15,    16,    17],
       [   18,    19,    20,    21,    22,    23],
       [   24,    25,    26,    27,    28,    29],
       [   30,    31,    32,    33,    34,    35],
       [   36,    37,    38,    39,    40,    41]])

In [93]:
practice.flags['OWNDATA'], practice_copied.flags['OWNDATA']

(True, True)

In [94]:
#### Code Challenge

In [95]:
quarterly_revenue_by_year = np.array([
    [22.72, 29.13, 25.36, 35.75],
    [29.13, 30.4, 32.71, 43.74],
    [35.71, 37.96, 43.74, 60.5]
])

In [106]:
quarterly_revenue_by_year[:2, 1::2]

array([[29.13, 35.75],
       [30.4 , 43.74]])

In [107]:
high_scores = np.array(
    [1247700, 1234200, 1218000, 1206800, 1143100]
)

## Slicing returns a data view, so you're actually changing high_scores
first_couple = high_scores[:2]
first_couple[0] = 8675309

In [108]:
high_scores[0]

8675309

### Manipulation

In [111]:
practice_view = practice.reshape(3, 14)
practice, practice_view, practice_view.base is practice

(array([[90210,     1,     2,     3,     4,     5],
        [    6,     7,     8,     9,    10,    11],
        [   12,    13,    14,    15,    16,    17],
        [   18,    19,    20,    21,    22,    23],
        [   24,    25,    26,    27,    28,    29],
        [   30,    31,    32,    33,    34,    35],
        [   36,    37,    38,    39,    40,    41]]),
 array([[90210,     1,     2,     3,     4,     5,     6,     7,     8,
             9,    10,    11,    12,    13],
        [   14,    15,    16,    17,    18,    19,    20,    21,    22,
            23,    24,    25,    26,    27],
        [   28,    29,    30,    31,    32,    33,    34,    35,    36,
            37,    38,    39,    40,    41]]),
 True)

In [115]:
practice.reshape(-1, 2)

array([[90210,     1],
       [    2,     3],
       [    4,     5],
       [    6,     7],
       [    8,     9],
       [   10,    11],
       [   12,    13],
       [   14,    15],
       [   16,    17],
       [   18,    19],
       [   20,    21],
       [   22,    23],
       [   24,    25],
       [   26,    27],
       [   28,    29],
       [   30,    31],
       [   32,    33],
       [   34,    35],
       [   36,    37],
       [   38,    39],
       [   40,    41]])

In [116]:
practice.reshape(-1, 2).shape

(21, 2)

In [117]:
practice

array([[90210,     1,     2,     3,     4,     5],
       [    6,     7,     8,     9,    10,    11],
       [   12,    13,    14,    15,    16,    17],
       [   18,    19,    20,    21,    22,    23],
       [   24,    25,    26,    27,    28,    29],
       [   30,    31,    32,    33,    34,    35],
       [   36,    37,    38,    39,    40,    41]])

In [121]:
# This creates a view - ravel returns a contiguous, flattened array:
practice.ravel()

array([90210,     1,     2,     3,     4,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29,    30,    31,    32,    33,    34,    35,
          36,    37,    38,    39,    40,    41])

In [123]:
# Look up stuff:
np.lookfor("flat")

Search results for 'flat'
-------------------------
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.flatiter
    Flat iterator object to iterate over arrays.
numpy.put
    Replaces specified elements of an array with given values.
numpy.flatnonzero
    Return indices that are non-zero in the flattened version of a.
numpy.ravel
    Return a contiguous flattened array.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.unravel_index
    Converts a flat index or array of flat indices into a tuple
numpy.matrix.flatten
    Return a flattened copy of the matrix.
numpy.ma.flatten_mask
    Returns a completely flattened version of the mask, where nested fields
numpy.chararray.flatten
    Return a copy of the array collapsed into one dimension.
numpy.chararray.put
    Set ``a.flat[n] = values[n]`` for all `n` in indices.
numpy.ravel_multi_index
    Converts a tuple of index arrays into an array of fl

In [125]:
# Look up specific method
np.ravel?

In [126]:
# Flatten creates a copy collapsed into one dimension:
practice.flatten()

array([90210,     1,     2,     3,     4,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29,    30,    31,    32,    33,    34,    35,
          36,    37,    38,    39,    40,    41])

In [127]:
np.reshape?

#### Quiz
* Reshape creates a data view, not a copy.

## Array Programming

### New Way of Thinking